baseURL = ''
relativeURLs = "True"
languageCode = 'en-us'
title = 'GPA Consulting Ltd.'
theme = "hugo-scroll"

[security]
    enableInlineShortcodes = "true"

[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/gpa-consulting-logo-ezgif.com-avif-to-png-converter.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "GPA Consulting Ltd - Delegated Binding Authority Auditing"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Your partners in binding authority assurance services"

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© GPA Consulting Ltd."

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = false

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false

    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = false

    # Show links indicated with footer_menu and footer_menu_title in the footer of the page
    showFooterLinks = false

    [params.meta]
        keywords = "insurer, service, delivery, focus, scopes, claims, processes, report, adherence, market, technical, underwriting, experience, remote, personal, coverholder, agents, client, audits, review, audited, administrators, contract, staff, insurance, directors, principles, considerable, modular, support, customer, conscious, conduct, consulting, bespoke, travel, lloyd’s, operations, developed, findings, management, authority, comprehensive, requirements, partner, regulation, industry, discuss, onsite"

    [[params.contacts]]
        label = "phone"
        value = "+49 1111 555555"
        url = "tel:+49 1111 555555"
        icon = "fa fa-phone"

    [[params.contacts]]
        label = "email"
        value = "mail@janedoe.com"
        url = "mailto:mail@janedoe.com"
        icon = "fa fa-envelope"
